model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "./sd-models/model.safetensors"
train_data_dir = "./train/aki"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = ""
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
save_state = false
max_train_epochs = 30
train_batch_size = 6
gradient_checkpointing = true
gradient_accumulation_steps = 4
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.00005
lr_scheduler = "cosine"
lr_warmup_steps = 0
optimizer_type = "AdamW8bit"
network_module = "lycoris.kohya"
network_dim = 100000
network_alpha = 100000
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
max_token_length = 255
seed = 1337
mixed_precision = "bf16"
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
network_args = [
  "conv_dim=100000",
  "conv_alpha=100000",
  "dropout=0",
  "algo=lokr",
  "factor=3"
]
v_parameterization = true
