[general]
enable_bucket = true                        # 是否使用Aspect Ratio Bucketing

[[datasets]]
resolution = 1024                           # 训练分辨率
batch_size = 2                              # 批次大小

  [[datasets.subsets]]
  image_dir = 'train_database\test_face'                     # 指定包含训练图像的文件夹
  class_tokens = ''                # 指定标识符类
  num_repeats = 10                          # 训练图像的重复次数
