model_type = "flux"
pretrained_model_name_or_path = "./models/flux1-dev-fp8.safetensors"
ae = "./models/ae.safetensors"
clip_l = "./models/clip_l.safetensors"
t5xxl = "./models/t5xxl_fp16.safetensors"
resume = ""
timestep_sampling = "sigma"
sigmoid_scale = 1.0
model_prediction_type = "raw"
discrete_flow_shift = 1.0
loss_type = "l2"
guidance_scale = 1.0
train_t5xxl = false
apply_t5_attn_mask = true
train_data_dir = "./train_database/test1"
prior_loss_weight = 1
resolution = "768,768"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "aki"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
save_state = false
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 1e-5
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora_flux"
network_dim = 2
network_alpha = 16
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
sdpa = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = true
fp8_base = true
